package nextcompile

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

func TestRouteToRegex(t *testing.T) {
	cases := []struct {
		route      string
		wantRegex  string
		wantParams []string
		// Concrete URLs: paths that should match, paths that should not.
		matchOK   []string
		matchFail []string
	}{
		{
			route:      "/blog/[slug]",
			wantRegex:  `/^\/blog\/([^/]+)\/?$/`,
			wantParams: []string{"slug"},
			matchOK:    []string{"/blog/hello", "/blog/my-post/", "/blog/%20space"},
			matchFail:  []string{"/blog", "/blog/a/b", "/other/a"},
		},
		{
			route:      "/shop/[...path]",
			wantRegex:  `/^\/shop\/(.+?)\/?$/`,
			wantParams: []string{"path"},
			matchOK:    []string{"/shop/a", "/shop/a/b/c"},
			matchFail:  []string{"/shop", "/other"},
		},
		{
			route:      "/users/[id]/posts/[pid]",
			wantParams: []string{"id", "pid"},
			matchOK:    []string{"/users/42/posts/99"},
			matchFail:  []string{"/users/42", "/users/42/posts"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.route, func(t *testing.T) {
			got, params := routeToRegex(tc.route)
			if tc.wantRegex != "" && got != tc.wantRegex {
				t.Errorf("regex: got %s, want %s", got, tc.wantRegex)
			}
			if !stringSlicesEqual(params, tc.wantParams) {
				t.Errorf("params: got %v, want %v", params, tc.wantParams)
			}
			// Translate to a Go regex and confirm the semantics behave the way
			// the runtime will. Convert JS /.../ literal to Go source by
			// stripping delimiters and unescaping \/.
			goPattern := strings.ReplaceAll(got[1:len(got)-1], `\/`, `/`)
			re := regexp.MustCompile(goPattern)
			for _, ok := range tc.matchOK {
				if !re.MatchString(ok) {
					t.Errorf("expected match for %q against %s", ok, goPattern)
				}
			}
			for _, no := range tc.matchFail {
				if re.MatchString(no) {
					t.Errorf("expected no match for %q against %s", no, goPattern)
				}
			}
		})
	}
}

func TestDynamicSpecificity(t *testing.T) {
	cases := []struct {
		a, b     string
		aMoreThan bool // a score > b score?
	}{
		{"/users/[id]/posts", "/users/[...rest]", true},
		{"/a/b/c", "/a/b/[x]", true},
		{"/docs/[[...slug]]", "/docs/[slug]", false},
	}
	for _, tc := range cases {
		sa, sb := dynamicSpecificity(tc.a), dynamicSpecificity(tc.b)
		if tc.aMoreThan && sa <= sb {
			t.Errorf("expected %q (score %d) > %q (score %d)", tc.a, sa, tc.b, sb)
		}
		if !tc.aMoreThan && sa >= sb {
			t.Errorf("expected %q (score %d) < %q (score %d)", tc.a, sa, tc.b, sb)
		}
	}
}

func TestRenderDispatchTable_StaticAndDynamic(t *testing.T) {
	refs := []ModuleRef{
		{RoutePath: "/", Kind: RouteKindPage, CompiledPath: ".next/server/app/page.js"},
		{RoutePath: "/api/users", Kind: RouteKindAPI, CompiledPath: ".next/server/app/api/users/route.js"},
		{RoutePath: "/blog/[slug]", Kind: RouteKindPage, CompiledPath: ".next/server/app/blog/[slug]/page.js"},
		{RoutePath: "/_middleware", Kind: RouteKindMiddleware, CompiledPath: ".next/server/middleware.js"},
	}
	src := renderDispatchTable(refs, nil)

	// Must contain generated header.
	if !strings.Contains(src, "GENERATED BY nextcompile") {
		t.Error("missing header")
	}
	// Static routes in staticTable.
	if !strings.Contains(src, `"/": { kind: "page", usesRSC: false, hasActions: false, ppr: false,`) {
		t.Errorf("missing root entry:\n%s", src)
	}
	if !strings.Contains(src, `"/api/users": { kind: "api", usesRSC: false, hasActions: false, ppr: false,`) {
		t.Errorf("missing api entry:\n%s", src)
	}
	// Dynamic route in dynamicTable with compiled regex.
	if !strings.Contains(src, `"/blog/[slug]"`) || !strings.Contains(src, `pattern: /^\/blog\/`) {
		t.Errorf("missing dynamic entry:\n%s", src)
	}
	// Middleware ref.
	if !strings.Contains(src, `export const middlewareRef = { compiled:`) {
		t.Errorf("missing middlewareRef:\n%s", src)
	}
	// Import paths must go one level up (past _nextdeploy/).
	if !strings.Contains(src, `import("../.next/server/app/page.js")`) {
		t.Errorf("wrong import path:\n%s", src)
	}
}

func TestRenderDispatchTable_NoMiddleware(t *testing.T) {
	src := renderDispatchTable([]ModuleRef{
		{RoutePath: "/", Kind: RouteKindPage, CompiledPath: "server/app/page.js"},
	}, nil)

	if !strings.Contains(src, "export const middlewareRef = null;") {
		t.Errorf("expected null middlewareRef:\n%s", src)
	}
}

func TestEmitDispatchTable_WritesFile(t *testing.T) {
	dir := t.TempDir()
	refs := []ModuleRef{
		{RoutePath: "/", Kind: RouteKindPage, CompiledPath: "server/app/page.js"},
	}
	path, err := EmitDispatchTable(refs, nil, dir)
	if err != nil {
		t.Fatalf("EmitDispatchTable: %v", err)
	}
	if exp := filepath.Join(dir, "_nextdeploy", "dispatch.mjs"); path != exp {
		t.Errorf("path: got %s, want %s", path, exp)
	}
	data, err := os.ReadFile(path) // #nosec G304
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "export const staticTable") {
		t.Errorf("file content:\n%s", data)
	}
}

func stringSlicesEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
